services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=podcast

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

  backend:
    build:
      context: backend
      dockerfile: dev.dockerfile
    ports:
      - 3111:3111
    volumes:
      - "./backend/:/app"
    environment:
      - "Connection_string=postgres://bob:password@db:5432/podcast?sslmode=disable"
    depends_on:
      - db

  frontend:
    container_name: podcast_frontend
    build:
      context: frontend
      target: builder
    restart: always
    command: npm run dev
    # develop:
    #   watch:
    #     - action: sync
    #       path: /app/web
    #       target: /app/web
    #       ignore:
    #         - node_modules/
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - BACKEND_URL=http://backend:3111
    ports:
      - 3000:3000
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
      - "/app/.next"
    depends_on:
      - backend
