services:
  backend:
    build:
      context: backend
      dockerfile: dev.dockerfile
    restart: always
    ports:
      - 3111:3111
    volumes:
      - "./backend:/app"

  frontend:
    build:
      context: frontend
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: /app/web
          target: /app/web
          ignore:
            - node_modules/
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000

    volumes:
      - "./frontend:/app"
    depends_on:
      - backend
