CREATE TABLE IF NOT EXISTS hot_take (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    presenter INT NOT NULL,
    episode INT NOT NULL,
    content Varchar(255),
    tags JSONB,
    result int,
    created_date DATE,
    due_date DATE
)
